spring.application.name=Astrocash
spring.data.mongodb.uri=mongodb://localhost:27017/astrocash
spring.data.mongodb.database=astrocash

jwt.secret=chaveSuperSecretaParaJwt12345678
# 1 hora em milissegundos
jwt.expiration=3600000
